# Generated by Django 3.2.13 on 2022-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especializados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=150)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('FechaModificacion', models.DateField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(max_length=150)),
                ('UsuarioModificacion', models.CharField(max_length=150)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
    ]
