# Generated by Django 3.2.13 on 2022-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicosEspecialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicoId', models.CharField(max_length=150)),
                ('Especialidad', models.CharField(max_length=150)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('FechaModificacion', models.DateField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(max_length=150)),
                ('UsuarioModificacion', models.CharField(max_length=150)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Especializados',
            new_name='Especializades',
        ),
    ]
