# Generated by Django 3.2.13 on 2022-06-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_auto_20220604_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Dni', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('NumColegiatura', models.CharField(max_length=30)),
                ('FechaNacimiento', models.DateField()),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('FechaModificacion', models.DateField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(max_length=30)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicosEspecialidades',
        ),
        migrations.AlterField(
            model_name='especializades',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='especializades',
            name='UsuarioModificacion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='especializades',
            name='UsuarioRegistro',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='medicos',
            name='EspecialidadId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.especializades'),
        ),
    ]
