# Generated by Django 3.2.13 on 2022-06-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0004_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.DateField(default=False)),
                ('InicioAtencio', models.DateTimeField(default=False)),
                ('FinAtencion', models.DateTimeField(default=False)),
                ('Activo', models.BooleanField(default=True)),
                ('FechaRegistro', models.DateField(default=True)),
                ('UsuarioRegistro', models.CharField(max_length=50)),
                ('FechaModificacion', models.DateField(default=True)),
                ('UsuarioModificacion', models.CharField(max_length=50)),
                ('MedicoId', models.ManyToManyField(to='hospitalApp.Medicos')),
            ],
        ),
    ]
