# Generated by Django 3.2.13 on 2022-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0005_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='FechaAtencion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='FechaModificacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='FinAtencion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='InicioAtencio',
            field=models.DateTimeField(),
        ),
    ]
