# Generated by Django 3.2.13 on 2022-06-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0006_auto_20220604_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAtencion', models.DateField()),
                ('InicioAtencion', models.DateTimeField()),
                ('FinAtencion', models.DateTimeField()),
                ('Estado', models.BooleanField(default=True)),
                ('Observaciones', models.TextField()),
                ('Activo', models.BooleanField(default=True)),
                ('FechaRegistro', models.CharField(max_length=50)),
                ('UsuarioRegistro', models.CharField(max_length=50)),
                ('FechaModificacion', models.DateField(auto_now_add=True)),
                ('UsuarioModificacion', models.CharField(max_length=50)),
                ('MedicoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medicos')),
                ('PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.pacientes')),
            ],
        ),
    ]
