# Generated by Django 3.2.13 on 2022-06-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0007_citas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especializades',
            new_name='Especialidades',
        ),
    ]
