# Generated by Django 3.2.13 on 2022-06-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0008_rename_especializades_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='Descripcion',
            field=models.TextField(),
        ),
    ]
