# Generated by Django 3.2.14 on 2022-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0012_alter_pacientes_photocopy_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='photocopy_document',
            field=models.FileField(upload_to='media/'),
        ),
    ]
