# Generated by Django 3.2.14 on 2022-07-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0013_alter_pacientes_photocopy_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='photocopy_document',
            new_name='document',
        ),
    ]
