# Generated by Django 3.2.14 on 2022-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0014_rename_photocopy_document_pacientes_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='document',
        ),
    ]
