# Generated by Django 3.2.14 on 2022-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0015_remove_pacientes_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='pacientes/', verbose_name='Documento'),
        ),
    ]
