# Generated by Django 3.2.14 on 2022-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0017_alter_pacientes_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='document',
            field=models.FileField(upload_to='pacientesFiles/', verbose_name='Documento'),
        ),
    ]
